# Generated by Django 3.2.5 on 2021-07-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribing',
            options={'verbose_name': 'Subscribe'},
        ),
    ]
